# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
## Check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=2.0.1
maven_group=dev.dfonline
archives_base_name=CodeClient

# Dependencies
fabric_api_version=0.158.0+26.2
modmenu_version=20.0.1
yacl_version=3.9.6+26.2-fabric
adventure_api_version=5.2.0
adventure_fabric_version=7.1.1
